PacientifyWeb/Models/ErrorViewModel.cs
namespace PacientifyWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PacientifyWeb/Controllers/AppointmentsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PacientifyWeb.Controllers
{
    public class AppointmentsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PacientifyWeb/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace PacientifyWeb.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
    }
}

PacientifyWeb/Controllers/DoctorsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PacientifyWeb.Controllers
{
    public class DoctorsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PacientifyWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PacientifyWeb.Models;
using System.Diagnostics;

namespace PacientifyWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PacientifyWeb/Controllers/LaboratoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace PacientifyWeb.Controllers
{
    public class LaboratoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PacientifyWeb/Controllers/PatientsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PacientifyWeb.Controllers
{
    public class PatientsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PacientifyWeb/Controllers/TestsLaboratoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace PacientifyWeb.Controllers
{
    public class TestsLaboratoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PacientifyWeb/Controllers/UsersController.cs
//using Microsoft.AspNetCore.Mvc;
//using Pacientify.Core.Application.Services;
//using Pacientify.Core.Domain.Entities;
//using System.Collections.Generic;
//using System.Threading.Tasks;

//namespace PacientifyWeb.Controllers

//{
//    public class UsersController : Controller
//    {
//        private readonly UserService _userService;
//        public UserController(UserService userService)
//        {
//            _userService = userService;
//        }

//        public async Task<IActionResult> Index()
//        {
//            var users = await _userService.GetAllUsersAsync();
//            return View(users);
//        }

//        public IActionResult Create()
//        {
//            return View();
//        }

//        [HttpPost]
//        public async Task<IActionResult> Create(User user)
//        {
//            await _userService.CreateUserAsync(user);
//            return RedirectToAction("Index");
//        }

//        public async Task<IActionResult> Edit(int id)
//        {
//            var user = await _userService.GetUserByIdAsync(id);
//            return View(user);
//        }

//        [HttpPost]
//        public async Task<IActionResult> Edit(User user)
//        {
//            await _userService.UpdateUserAsync(user);
//            return RedirectToAction("Index");
//        }

//        public async Task<IActionResult> Delete(int id)
//        {
//            await _userService.DeleteUserAsync(id);
//            return RedirectToAction("Index");
//        }
//    }
//}


using Microsoft.AspNetCore.Mvc;
using Pacientify.Core.Domain.Entities;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PacientifyWeb.Controllers
{
    public class UsersController : Controller
    {

        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

PacientifyWeb/Views/Appointments/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Appointments/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Appointments/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Doctors/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Doctors/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Doctors/Index.cshtml
<div class="container mx-auto my-20 px-4">
    <h1 class="text-3xl font-semibold mb-4 text-gray-600">Mantenimiento de Médicos</h1>
    <br>
    <div class="mt-4">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded">
            Crear Médico
        </button>
    </div>
    <br>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        <a href="#" class="relative block overflow-hidden rounded-lg border border-gray-100 p-4 sm:p-6 lg:p-8">
            <span
                class="absolute inset-x-0 bottom-0 h-2 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"></span>

            <div class="sm:flex sm:justify-between sm:gap-4">
                <div>
                    <h3 class="text-lg font-bold text-gray-900 sm:text-xl">
                        Dr. Juan Pérez
                    </h3>
                    <p class="mt-1 text-xs font-medium text-gray-600">Cirujano</p>
                </div>
                <div class="hidden sm:block sm:shrink-0">
                    <img alt="Dr. Juan Pérez"
                        src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80"
                        class="h-16 w-16 rounded-lg object-cover shadow-sm" />
                </div>
            </div>

            <div class="mt-4">
                <p class="max-w-[40ch] text-sm text-gray-500">
                    Dr. Juan Pérez es un cirujano con años de experiencia en cirugía cardiovascular.
                </p>
            </div>

            <dl class="mt-6 flex gap-4 sm:gap-6">
                <div class="flex flex-col">
                    <dt class="text-sm font-medium text-gray-600">Correo</dt>
                    <dd class="text-xs text-gray-500">juan.perez@example.com</dd>
                </div>

                <div class="flex flex-col">
                    <dt class="text-sm font-medium text-gray-600">Teléfono</dt>
                    <dd class="text-xs text-gray-500">123-456-7890</dd>
                </div>
            </dl>

            <div class="mt-6">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-medium py-1 px-2 rounded">
                    <i class="fa fa-pencil"></i> Editar
                </button>
                <button class="bg-red-500 hover:bg-red-700 text-white font-medium py-1 px-2 rounded ml-2">
                    <i class="fa fa-trash"></i> Eliminar
                </button>
            </div>
        </a>

        <a href="#" class="relative block overflow-hidden rounded-lg border border-gray-100 p-4 sm:p-6 lg:p-8">
            <span
                class="absolute inset-x-0 bottom-0 h-2 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"></span>

            <div class="sm:flex sm:justify-between sm:gap-4">
                <div>
                    <h3 class="text-lg font-bold text-gray-900 sm:text-xl">
                        Dr. Luis Alvarado
                    </h3>
                    <p class="mt-1 text-xs font-medium text-gray-600">Cirujano</p>
                </div>
                <div class="hidden sm:block sm:shrink-0">
                    <img alt="Dr. Juan Pérez"
                        src="https://images.unsplash.com/photo-1622253692010-333f2da6031d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1964&q=80"
                        class="h-16 w-16 rounded-lg object-cover shadow-sm" />
                </div>
            </div>

            <div class="mt-4">
                <p class="max-w-[40ch] text-sm text-gray-500">
                    Dr. Juan Pérez es un cirujano con años de experiencia en cirugía cardiovascular.
                </p>
            </div>

            <dl class="mt-6 flex gap-4 sm:gap-6">
                <div class="flex flex-col">
                    <dt class="text-sm font-medium text-gray-600">Correo</dt>
                    <dd class="text-xs text-gray-500">juan.perez@example.com</dd>
                </div>

                <div class="flex flex-col">
                    <dt class="text-sm font-medium text-gray-600">Teléfono</dt>
                    <dd class="text-xs text-gray-500">123-456-7890</dd>
                </div>
            </dl>

            <div class="mt-6">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-medium py-1 px-2 rounded">
                    <i class="fa fa-pencil"></i> Editar
                </button>
                <button class="bg-red-500 hover:bg-red-700 text-white font-medium py-1 px-2 rounded ml-2">
                    <i class="fa fa-trash"></i> Eliminar
                </button>
            </div>
        </a>

        <a href="#" class="relative block overflow-hidden rounded-lg border border-gray-100 p-4 sm:p-6 lg:p-8">
            <span
                class="absolute inset-x-0 bottom-0 h-2 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"></span>

            <div class="sm:flex sm:justify-between sm:gap-4">
                <div>
                    <h3 class="text-lg font-bold text-gray-900 sm:text-xl">
                        Dra. Maria Rodriguez
                    </h3>
                    <p class="mt-1 text-xs font-medium text-gray-600">Pediatra</p>
                </div>
                <div class="hidden sm:block sm:shrink-0">
                    <img alt="Dra. Maria Rodriguez"
                        src="https://images.unsplash.com/photo-1594824476967-48c8b964273f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1887&q=80"
                        class="h-16 w-16 rounded-lg object-cover shadow-sm" />
                </div>
            </div>

            <div class="mt-4">
                <p class="max-w-[40ch] text-sm text-gray-500">
                    Dra. Maria Rodriguez es una pediatra especializada en cuidado infantil.
                </p>
            </div>

            <dl class="mt-6 flex gap-4 sm:gap-6">
                <div class="flex flex-col">
                    <dt class="text-sm font-medium text-gray-600">Correo</dt>
                    <dd class="text-xs text-gray-500">maria.rodriguez@example.com</dd>
                </div>

                <div class="flex flex-col">
                    <dt class="text-sm font-medium text-gray-600">Teléfono</dt>
                    <dd class="text-xs text-gray-500">987-654-3210</dd>
                </div>
            </dl>

            <div class="mt-6">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-medium py-1 px-2 rounded">
                    <i class="fa fa-pencil"></i> Editar
                </button>
                <button class="bg-red-500 hover:bg-red-700 text-white font-medium py-1 px-2 rounded ml-2">
                    <i class="fa fa-trash"></i> Eliminar
                </button>
            </div>
        </a>

        <a href="#" class="relative block overflow-hidden rounded-lg border border-gray-100 p-4 sm:p-6 lg:p-8">
            <span
                class="absolute inset-x-0 bottom-0 h-2 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"></span>

            <div class="sm:flex sm:justify-between sm:gap-4">
                <div>
                    <h3 class="text-lg font-bold text-gray-900 sm:text-xl">
                        Dra. Angela Marte
                    </h3>
                    <p class="mt-1 text-xs font-medium text-gray-600">Pediatra</p>
                </div>
                <div class="hidden sm:block sm:shrink-0">
                    <img alt="Dra. Maria Rodriguez"
                        src="https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80"
                        class="h-16 w-16 rounded-lg object-cover shadow-sm" />
                </div>
            </div>

            <div class="mt-4">
                <p class="max-w-[40ch] text-sm text-gray-500">
                    Dra. Maria Rodriguez es una pediatra especializada en cuidado infantil.
                </p>
            </div>

            <dl class="mt-6 flex gap-4 sm:gap-6">
                <div class="flex flex-col">
                    <dt class="text-sm font-medium text-gray-600">Correo</dt>
                    <dd class="text-xs text-gray-500">maria.rodriguez@example.com</dd>
                </div>

                <div class="flex flex-col">
                    <dt class="text-sm font-medium text-gray-600">Teléfono</dt>
                    <dd class="text-xs text-gray-500">987-654-3210</dd>
                </div>
            </dl>

            <div class="mt-6">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-medium py-1 px-2 rounded">
                    <i class="fa fa-pencil"></i> Editar
                </button>
                <button class="bg-red-500 hover:bg-red-700 text-white font-medium py-1 px-2 rounded ml-2">
                    <i class="fa fa-trash"></i> Eliminar
                </button>
            </div>
        </a>
    </div>
    <br />
</div>
</div>

PacientifyWeb/Views/Home/Menu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Laboratory/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Laboratory/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Laboratory/Index.cshtml
@*
For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Patients/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Patients/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Patients/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaDePacientes</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.15/dist/tailwind.min.css"
        integrity="sha384-w9TqUD7lBtF+X7R+A9/j2uFOKwZb3m8lX1ZMxJcg7gG5mgy8Ij90El+bsQOjFL5dQ" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDePacientes.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
</head>

<body class="font-poppins">
    <header>
        <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
                <a href="#" class="flex items-center">
                    <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo" />
                </a>
                <div class="flex items-center lg:order-2">
                    <a asp-controller="Auth" asp-action="Login"
                        class="text-blue-700 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 focus:outline-none">Iniciar
                        Sesion</a>

                    <a asp-controller="Auth" asp-action="Register"
                        class="bg-blue-700 text-white font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 focus:outline-none">Registrarse</a>
                </div>
                <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
                    <ul class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
                         <li>
                            <a asp-controller="Home" asp-action="Index"
                                class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 lg:border-0 lg:p-0 dark:text-gray-400 dark:border-gray-700 transition-all duration-300 ease-in-out hover:text-blue-700">Home</a>
                        </li>
                        <li>
                            <a asp-controller="Users" asp-action="Index"
                                class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 lg:border-0 lg:p-0 dark:text-gray-400 dark:border-gray-700 transition-all duration-300 ease-in-out hover:text-blue-700">Usuarios</a>
                        </li>
                        <li>
                            <a asp-controller="Doctors" asp-action="Index"
                                class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 lg:border-0 lg:p-0 dark:text-gray-400 dark:border-gray-700 transition-all duration-300 ease-in-out hover:text-blue-700"
                                aria-current="page">Médicos</a>
                        </li>
                        <li>
                            <a asp-controller="TestsLaboratory" asp-action="Index"
                                class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 lg:border-0 lg:p-0 dark:text-gray-400 dark:border-gray-700 transition-all duration-300 ease-in-out hover:text-blue-700"
                                aria-current="page">Pruebas de Laboratorio</a>
                        </li>
                        <li>
                            <a asp-controller="Patients" asp-action="Index"
                                class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 lg:border-0 lg:p-0 dark:text-gray-400 dark:border-gray-700 transition-all duration-300 ease-in-out hover:text-blue-700"
                                aria-current="page">Pacientes</a>
                        </li>
                        <li>
                            <a asp-controller="Appointments" asp-action="Index"
                                class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 lg:border-0 lg:p-0 dark:text-gray-400 dark:border-gray-700 transition-all duration-300 ease-in-out hover:text-blue-700"
                                aria-current="page">Citas</a>
                        </li>
                        <li>
                            <a asp-controller="Laboratory" asp-action="Index"
                                class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 lg:border-0 lg:p-0 dark:text-gray-400 dark:border-gray-700 transition-all duration-300 ease-in-out hover:text-blue-700"
                                aria-current="page">Resultados de Laboratorio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container mx-auto mt-8">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

PacientifyWeb/Views/TestsLaboratory/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/TestsLaboratory/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PacientifyWeb/Views/TestsLaboratory/Index.cshtml
<div class="container mx-auto my-20 px-4">
    <h1 class="text-3xl font-semibold mb-4 text-gray-600">Mantenimiento de Pruebas de Laboratorio</h1>
    <br>
    <div class="mt-4">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded">
            Crear Prueba de Laboratorio
        </button>
    </div>
    <br>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        <article class="rounded-xl border-2 border-gray-100 bg-white">
            <div class="flex items-start gap-4 p-4 sm:p-6 lg:p-8">
                <a href="#" class="block shrink-0">
                    <img alt="Prueba de Laboratorio" src="URL_DE_LA_IMAGEN" class="h-14 w-14 rounded-lg object-cover" />
                </a>

                <div>
                    <h3 class="font-medium sm:text-lg">
                        <a href="#" class="hover:underline">Nombre de la Prueba 1</a>
                    </h3>

                    <p class="line-clamp-2 text-sm text-gray-700">
                        Descripción de la Prueba de Laboratorio 1.
                    </p>
                </div>
            </div>

            <div class="flex justify-end">
                <strong
                    class="-mb-[2px] -me-[2px] inline-flex items-center gap-1 rounded-ee-xl rounded-ss-xl bg-green-500 px-3 py-1.5 text-white">
                    <i class="fas fa-check-circle text-[10px] font-medium sm:text-xs"></i>
                    <span class="text-[10px] font-medium sm:text-xs">Completado</span>
                </strong>
            </div>

        </article>


        <article class="rounded-xl border-2 border-gray-100 bg-white">
            <div class="flex items-start gap-4 p-4 sm:p-6 lg:p-8">
                <a href="#" class="block shrink-0">
                    <img alt="Prueba de Laboratorio" src="URL_DE_LA_IMAGEN" class="h-14 w-14 rounded-lg object-cover" />
                </a>

                <div>
                    <h3 class="font-medium sm:text-lg">
                        <a href="#" class="hover:underline">Nombre de la Prueba 1</a>
                    </h3>

                    <p class="line-clamp-2 text-sm text-gray-700">
                        Descripción de la Prueba de Laboratorio 1.
                    </p>
                </div>
            </div>

            <div class="flex justify-end">
                <strong
                    class="-mb-[2px] -me-[2px] inline-flex items-center gap-1 rounded-ee-xl rounded-ss-xl bg-yellow-500 px-3 py-1.5 text-white">
                    <i class="fas fa-clock text-[10px] font-medium sm:text-xs"></i>
                    <span class="text-[10px] font-medium sm:text-xs">Pendiente</span>
                </strong>
            </div>

        </article>
    </div>
</div>

PacientifyWeb/Views/Users/Create.cshtml
@* @model Core.Domain.Entities.User

@{
    ViewData["Title"] = "Crear Usuario";
}

<h1 class="text-3xl font-semibold mb-4 text-gray-600">Crear Usuario</h1>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="FirstName" class="control-label"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Username" class="control-label"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IsAdmin" class="control-label"></label>
        <input asp-for="IsAdmin" type="checkbox" class="form-control" />
        <span asp-validation-for="IsAdmin" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Crear" class="btn btn-primary" />
    </div>
</form>
 *@

PacientifyWeb/Views/Users/Edit.cshtml
@* @model Core.Domain.Entities.User

@{
    ViewData["Title"] = "Editar Usuario";
}

<h1 class="text-3xl font-semibold mb-4 text-gray-600">Editar Usuario</h1>

<form asp-action="Edit" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="FirstName" class="control-label"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Username" class="control-label"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IsAdmin" class="control-label"></label>
        <input asp-for="IsAdmin" type="checkbox" class="form-control" />
        <span asp-validation-for="IsAdmin" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>
</form>
 *@